version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: manikumarreddy06/vprodb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MY_SQL_PASSWORD=vprodbpass


  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
    - RABBITMQ DEFAULT USER=guest
    - RABBITMQ DEFAULT PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
    image: manikumarreddy06/vproapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapp

  vproweb:
    build:
      context: ./Docker-files/web
    image: manikumarreddy06/vproweb
    container_name: vproweb
    ports:
      - "80:80"
volumes:
  vproappdata: {}
  vprodbdata: {}





